apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: meugo

images:
- name: goapp
  newName: aneresdevops/argocd
  newTag: 90f0fd45fa58a5d72ddbc0f37802fb16153350fc
- name: meugo
  newName: aneresdevops/argocd
  newTag: e37a2099a83f455445ad876016f930b4ec6da4f3
