apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default

images:
- name: goapp
  newName: aneresdevops/argocd
  newTag: 146271848f968a94d12d597234d7e39ca149abf6
- name: meugo
  newName: aneresdevops/argocd
  newTag: e37a2099a83f455445ad876016f930b4ec6da4f3
