apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: meugo

images:
- name: goapp
  newName: aneresdevops/argocd
  newTag: b96d3f3e42316658755de046133c75d33b07bf07
- name: meugo
  newName: aneresdevops/argocd
  newTag: e37a2099a83f455445ad876016f930b4ec6da4f3
