apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: meugo

images:
- name: goapp
  newName: aneresdevops/argocd
  newTag: 1ab6d704ed6c7842a730b6cb8ce5af65f2af39d8
- name: meugo
  newName: aneresdevops/argocd
  newTag: e37a2099a83f455445ad876016f930b4ec6da4f3
