apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: meugo

images:
- name: goapp
  newName: aneresdevops/argocd
  newTag: 438e0ccce1d205de822d1f4f6f59ff7beed57466
- name: meugo
  newName: aneresdevops/argocd
  newTag: e37a2099a83f455445ad876016f930b4ec6da4f3
